### ISSUE TITLE
Error on `deploy-reqs`

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#106]
Just tried to `deploy-reqs` using shub master and got

```
Traceback (most recent call last):
  File "/Users/zehzinho/.virtualenv/ds/bin/shub", line 9, in <module>
    load_entry_point('shub==1.5.0', 'console_scripts', 'shub')()
  File "/Users/zehzinho/.virtualenv/ds/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zehzinho/.virtualenv/ds/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/zehzinho/.virtualenv/ds/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zehzinho/.virtualenv/ds/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zehzinho/.virtualenv/ds/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/zehzinho/Sources/scraping-hub/shub/shub/deploy_reqs.py", line 34, in cli
    main(target, requirements_file)
  File "/Users/zehzinho/Sources/scraping-hub/shub/shub/deploy_reqs.py", line 43, in main
    utils.build_and_deploy_eggs(project, endpoint, apikey)
  File "/Users/zehzinho/Sources/scraping-hub/shub/shub/utils.py", line 141, in build_and_deploy_eggs
    build_and_deploy_egg(project, endpoint, apikey)
  File "/Users/zehzinho/Sources/scraping-hub/shub/shub/utils.py", line 168, in build_and_deploy_egg
    _deploy_dependency_egg(project, endpoint, apikey)
  File "/Users/zehzinho/Sources/scraping-hub/shub/shub/utils.py", line 183, in _deploy_dependency_egg
    make_deploy_request(url, data, files, auth)
TypeError: make_deploy_request() takes exactly 6 arguments (4 given)
```

**Comment by jdemaeyer** [comment]
OUCH. thanks
