### ISSUE TITLE
Check for entry points in setup.py

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#132]
Deploying fails with a quite cryptic (for users) message when setup.py does not contain a `scrapy` entry point that points it to the settings module:
https://paste.scrapinghub.com/show/8940/

If there's no `setup.py`, shub writes our own that has all the necessary information. But if the user wrote one, we probably should check whether the entry point exists and tell them to add it if necessary (or add it ourselves).

**Comment by lwm** [comment]
Looks like this one is done then? I just saw:

``` bash
λ ~/foo/bar/ master shub deploy
Target project ID: 218421
Saving project 218421 as default target. You can deploy to it via 'shub deploy' from now on
Saved to /home/foo/bar/scrapinghub.yml.
Packing version 3815722-master
Deploying to Scrapy Cloud project "218421"
Deploy log last 30 lines:
 ---> c1f0f4094a3f
Step 3 : RUN chmod +x /kumo-entrypoint
 ---> Using cache
 ---> 86ff89981da4
Successfully built 86ff89981da4
Entrypoint container is created successfully
>>> Checking python dependencies
WARNING: There're some errors when doing pip-check:
Traceback (most recent call last):
  File "/usr/local/sbin/run-pipcheck", line 143, in <module>
    sys.exit(main())
  File "/usr/local/sbin/run-pipcheck", line 114, in main
    eggs_env = load_eggs()
  File "/usr/local/sbin/run-pipcheck", line 77, in load_eggs
    settings_module = activate_main_egg(main_project_egg[0])
  File "/usr/local/sbin/run-pipcheck", line 92, in activate_main_egg
    raise AttributeError(SCRAPY_SETTINGS_ENTRYPOINT_NOT_FOUND)
AttributeError: 
Scrapy settings entrypoint is not found under `scrapy` group.
Please, specify it in your setup.py in the following format:
setup(
    ...,
    entry_points = {'scrapy': ['settings = your_project.settings']},
    ...
)
Check the link for more details:
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points
```

**Comment by jdemaeyer** [comment]
You're right, got fixed in Scrapy Cloud! Thanks @lwm
