### ISSUE TITLE
deploy spider with webdriver

### ISSUE THREAD

**Issue by agiratech-arun** [scrapinghub/shub#178]
when i have deploy my spider to scrapinghub i have faced following error

`Error: Deploy failed (400):

---------- REMOTE TRACEBACK ----------
ERROR:root:Script initialization failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sh_scrapy/crawl.py", line 127, in _run_usercode
    _run(args, settings)
  File "/usr/lib/python2.7/dist-packages/sh_scrapy/crawl.py", line 87, in _run
    _run_scrapy(args, settings)
  File "/usr/lib/python2.7/dist-packages/sh_scrapy/crawl.py", line 95, in _run_scrapy
    execute(settings=settings)
  File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 209, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 115, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 296, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/lib/pymodules/python2.7/scrapy/spiderloader.py", line 30, in from_settings
    return cls(settings)
  File "/usr/lib/pymodules/python2.7/scrapy/spiderloader.py", line 21, in __init__
    for module in walk_modules(name):
  File "/usr/lib/pymodules/python2.7/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/eggs-J7iR5U/__main__.egg/onlineStore/spiders/flipkart.py", line 20, in <module>
  File "/tmp/eggs-J7iR5U/__main__.egg/onlineStore/spiders/flipkart.py", line 26, in FlipkartSpider
  File "/tmp/eggs-J7iR5U/selenium.egg/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary = capabilities.get("binary") or FirefoxBinary()
  File "/tmp/eggs-J7iR5U/selenium.egg/selenium/webdriver/firefox/firefox_binary.py", line 47, in __init__
    self._start_cmd = self._get_firefox_start_cmd()
  File "/tmp/eggs-J7iR5U/selenium.egg/selenium/webdriver/firefox/firefox_binary.py", line 157, in _get_firefox_start_cmd
    start_cmd = self.which(ffname)
  File "/tmp/eggs-J7iR5U/selenium.egg/selenium/webdriver/firefox/firefox_binary.py", line 205, in which
    for pe in os.environ['PATH'].split(os.pathsep):
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PATH'

---------- END OF REMOTE TRACEBACK ----------
`

**Comment by agiratech-arun** [comment]
i have found the problem that the selenium has trying to access the Firefox binary path, but it;s failed to get that.

**Comment by jdemaeyer** [comment]
Hey Arun,

my apologies for the late reply. Scrapy Cloud does currently not support Selenium.

I'm closing this because it's not an issue with `shub`, but feel free to contact Scrapinghub's support at support@scrapinghub.com or via the "Help" menu in your Scrapinghub dashboard if you have any questions.


Cheers,
-Jakob
