### ISSUE TITLE
copy-egg KeyError

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/shub#183]
```
(env) [PROJECT]$ shub copy-eggs
From which projects should I download eggs?: NNN
To which project should I upload eggs?: NNN
/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/shub/config.py:210: UserWarning: get_target is deprecated, use get_target_conf instead
  warnings.warn("get_target is deprecated, use get_target_conf instead")
Getting eggs list from project NNN...
Downloading eggs to /tmp/tmpW4qdeF/eggs-NNN.zip
Uncompressing: /tmp/tmpW4qdeF/eggs-NNN.zip
Traceback (most recent call last):
  File "/home/andrew/scraping/duproprio-crawler/env/bin/shub", line 11, in <module>
    sys.exit(cli())
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/shub/copy_eggs.py", line 30, in cli
    copy_eggs(project, endpoint, apikey, new_project, new_endpoint, new_apikey, copy_main)
  File "/home/andrew/scraping/duproprio-crawler/env/lib/python2.7/site-packages/shub/copy_eggs.py", line 47, in copy_eggs
    version = egg_versions[name]
KeyError: 'scrapy_crawlera-1.1.0-py2.7'
```

**Comment by andrewbaxter** [comment]
I can provide the project numbers via chat.

**Comment by jdemaeyer** [comment]
This arises from an inconsistency in the Dash API: When downloading eggs from  `https://dash.scrapinghub.com/api/eggs/bundle.zip` we will also get eggs that come with add-ons (e.g. `scrapy_crawlera`). However when listing project eggs via `https://dash.scrapinghub.com/api/eggs/list.json`, these eggs are omitted.

I've noticed the Dash team on whether that is on purpose and if not, whether they're going to fix it. Maybe we'll have to match egg names against a list of patterns to ignore.
