### ISSUE TITLE
AttributeError: 'module' object has no attribute 'wraps'

### ISSUE THREAD

**Issue by shashank-sharma** [scrapinghub/shub#239]
This is the error I am getting

vipul@shashank:~/Mythical/100day$ shub
Traceback (most recent call last):
  File "/usr/local/bin/shub", line 7, in <module>
    from shub.tool import cli
  File "/usr/local/lib/python3.4/dist-packages/shub/tool.py", line 56, in <module>
    command_module = importlib.import_module(module_path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.4/dist-packages/shub/image/__init__.py", line 23, in <module>
    command_module = importlib.import_module(module_path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.4/dist-packages/shub/image/deploy.py", line 132, in <module>
    wait_exponential_max=CHECK_RETRY_EXP_MAX)
  File "/usr/local/lib/python3.4/dist-packages/retrying.py", line 47, in wrap
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'

python version - Python 2.7.6
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)

Sorry if it is a stupid question but I am kind of stuck here.

**Comment by redapple** [comment]
Hi @shashank-sharma , it looks like shub requires (at least) `six>=1.7.0` because of [`six.wraps()`](https://github.com/benjaminp/six/blob/89ab315f5d216caf9edbc4dd88766124073901aa/CHANGES#L108).
Can you check what version of six you have in your environment? (`pip freeze` should show it)
If you indeed have `six` older than 1.7.0, can you try upgrading it? (with `pip install --upgrade six`)

**Comment by shashank-sharma** [comment]
I tried it, but still it's showing the exact same error. I am not sure but maybe it's related to the path difference. 

Version: six==1.10.0

**Comment by redapple** [comment]
Can you try using a virtualenv?

**Comment by shashank-sharma** [comment]
Great, it worked, All i have to do is create virtualenv with no site packages and then I downloaded shub again and then run it. 
I will try to run my code within virtualenv and deploy it easily.
