### ISSUE TITLE
TypeError on shub image deploy

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#288]
Hi, I'm getting this TypeError on `shub image deploy`:

```
TypeError: the JSON object must be str, not 'bytes'
 File "/Users/zehzinho/.venvs/sales-venv/lib/python3.5/site-packages/shub/image/deploy.py", line 81, in deploy_cmd
    username, password, email)
  File "/Users/zehzinho/.venvs/sales-venv/lib/python3.5/site-packages/shub/image/deploy.py", line 198, in _prepare_deploy_params
    metadata = list_mod.list_cmd(image_name, project, endpoint, apikey)
  File "/Users/zehzinho/.venvs/sales-venv/lib/python3.5/site-packages/shub/image/list.py", line 72, in list_cmd
    return _extract_metadata_from_image_info_output(logs)
  File "/Users/zehzinho/.venvs/sales-venv/lib/python3.5/site-packages/shub/image/list.py", line 139, in _extract_metadata_from_image_info_outpu
t
    metadata = json.loads(output)
  File "/Users/zehzinho/.pythonz/pythons/CPython-3.5.3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

and

```
$ ./shub-image-info

{
  "project_type": "other",
  "spiders": []
}
```

I'm using Python 3.5.3 on OSX.

**Comment by jdemaeyer** [comment]
Thanks again José! @vshlapakov could you take a look at this?

**Comment by vshlapakov** [comment]
@jdemaeyer Sure, I'll provide a patch, sorry for delay - missed it! Thanks @josericardo!

**Comment by Kamforka** [comment]
Hi there, I'm having a similar `TypeError` when executing `shub image deploy`:
```
Traceback (most recent call last):
  File "/home/macko/.local/bin/shub", line 11, in <module>
    sys.exit(cli())
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/macko/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/macko/.local/lib/python3.5/site-packages/shub/image/deploy.py", line 63, in cli
    apikey, insecure, async)
  File "/home/macko/.local/lib/python3.5/site-packages/shub/image/deploy.py", line 81, in deploy_cmd
    username, password, email)
  File "/home/macko/.local/lib/python3.5/site-packages/shub/image/deploy.py", line 198, in _prepare_deploy_params
    metadata = list_mod.list_cmd(image_name, project, endpoint, apikey)
  File "/home/macko/.local/lib/python3.5/site-packages/shub/image/list.py", line 72, in list_cmd
    return _extract_metadata_from_image_info_output(logs)
  File "/home/macko/.local/lib/python3.5/site-packages/shub/image/list.py", line 139, in _extract_metadata_from_image_info_output
    metadata = json.loads(output)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
Though `shub image build` and `shub image push` were free of errors.

I'm using Ubuntu 16.04 x64, Python3.5.2 and Scrapy1.4.0 and this is my Dockerfile:
```
FROM scrapinghub/scrapinghub-stack-scrapy:1.4-py3
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz && \
    tar xvfz geckodriver-v0.19.1-linux64.tar.gz && \
    chmod +x geckodriver && \
    mv geckodriver /usr/bin && \
    rm -f geckodriver

ENV TERM xterm
ENV SCRAPY_SETTINGS_MODULE my_project.settings
RUN mkdir -p /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python setup.py install
```

I also tried it for the first time with `FROM scrapinghub/scrapinghub-stack-scrapy:1.3`, as that one was the default.

**Comment by jdemaeyer** [comment]
Thanks for the report @Kamforka. It seems to be the same issue, we haven't released the fix to pypi yet. Can you try upgrading shub directly from the repository via `pip install git+https://github.com/scrapinghub/shub.git` to see if it is fixed?

**Comment by Kamforka** [comment]
@jdemaeyer I did just that and after rebuilding the whole image, the deployment just went fine!
Thank you.

**Comment by jdemaeyer** [comment]
Thanks for checking @Kamforka! We'll push a release to pypi soon.
