### ISSUE TITLE
shub deploy raises an exception

### ISSUE THREAD

**Issue by kmike** [scrapinghub/shub#298]
Hi!

I'm trying to deploy a project, but it raises the following error:

```
> shub deploy
Packing version 9367cd9-master
Deploying to Scrapy Cloud project "205008"
Deploy log last 30 lines:
 ---> f28bad26451d
Step 3/3 : RUN chmod +x /kumo-entrypoint
 ---> Using cache
 ---> f1e1f9e19546
Successfully built f1e1f9e19546
Entrypoint container is created successfully
>>> Checking python dependencies
WARNING: There're some errors when doing pip-check:
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python3.6/site-packages/pip/__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 6, in <module>
    import compileall
  File "/usr/local/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/app/python/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/app/python/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
{"message": "Dependencies check exit code: 1", "details": "Pip checks failed, please fix the conflicts", "error": "requirements_error"}

{"status": "error", "message": "Requirements error"}
Deploy log location: /var/folders/_5/cbsg50991szfp1r9nwxpx8580000gq/T/shub_deploy_46rws3li.log
Error: Deploy failed: b'{"status": "error", "message": "Requirements error"}'
```

~~requirements.txt file content (none of packages has `futures` as a direct dependency):~~

```
scrapy-cdr==0.5
scrapy-crawl-once==0.1.1
scrapy-kafka-export==0.1.1
w3lib==1.18.0
scrapinghub==2.0.0
boto==2.47.0
```

I'm using `scrapy:1.4-py3` stack.

**Comment by kmike** [comment]
Sorry, it seems one of them has.
